export const SET_CURRENT_DRAGGING = 'SET_CURRENT_DRAGGING';
export const SET_DRAGGING_POSITION = 'SET_DRAGGING_POSITION';
export const ADD_TO_CONSTRUCTOR = 'ADD_TO_CONSTRUCTOR';
export const REMOVE_FROM_CONSTRUCTOR = 'REMOVE_FROM_CONSTRUCTOR';